spring:
  application:
    name: mysql-demo
  ## mybatis 集成
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/technotes?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=GMT%2B8
    url: ${spring.datasource.jdbc-url}
    username: root
    password: kongyu12