spring:
  application:
    name: redis-demo
  redis:
    # 集群模式默认就是0库
    database: 0
    password: ThisisPass99!
    timeout: 10000
    cluster:
      nodes: 47.101.187.247:6379,47.101.187.247:6380
      max-redirects: 3
    jedis:
      #连接池最大连接数（使用负值表示没有限制
      max-active: 600
      #连接池最大阻塞等待时间（使用负值表示没有限制
      max-wait: 2000
      #连接池中的最大空闲连接
      max-idle: 600
      #连接池中的最小空闲连接
      min-idle: 10