spring:
  application:
    name: redis-demo
  redis:
    # ????????0?
    database: 0
    password: ThisisPass99!
    timeout: 10000
    cluster:
      nodes: 47.101.187.247:6379,47.101.187.247:6380,47.101.187.247:6381,47.101.187.247:6382,47.101.187.247:6383,47.101.187.247:6384
      max-redirects: 3
    jedis:
      pool:
        #???????????????????
        max-active: 600
        #??????????????????????
        max-wait: 2000
        #???????????
        max-idle: 600
        #???????????
        min-idle: 10